---
title: "SISBID_Day2"
output: html_document
---

```{r Install google sheets}
library (devtools)
install_github ("jennybc/googlesheets")
#install.packages("googlesheets")
library(googlesheets)
```

```{r read in the data}
sheets_url = "https://docs.google.com/spreadsheets/d/18KQQd4LY5k8Ucux1MvWCsQGQJlvd0ECTnn-3ixdOKFM/pubhtml"
gsurl1 = gs_url(sheets_url)
dat = gs_read (gsurl1, range = cell_rows(1:5))
dat = gs_read(gsurl1)
dat
```


## Doing JSON stuff now

Read In JSON

## Doing rvest
```{r rvest}
recount_url = "https://raw.githubusercontent.com/SISBID/Module1/gh-pages/labs/bioc-software.html"
install.packages("rvest")
library(rvest)
htmlfile = read_html(recount_url)


nds = html_nodes(htmlfile, xpath='//*[@id="biocViews_package_table"]')
dat = html_table(nds)
dat = as.data.frame(dat)
head(dat)
text = paste(dat[,3], collapse=" ")
install.packages(c("wordcloud","tm"))
library (wordcloud)
library(tm)
wordcloud(text,max.words=50)
```




## Doing APIs

```{r API chunk}

library(jsonlite)

oct4_dat = fromJSON("http://rest.ensembl.org//lookup/id/ENSG00000141510?content-type=application/json;expand=1")

#install.packages("jsonlite")
```



